#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { auditExtension } from '../src/analyzer.js';
import { loadCatalog } from '../src/catalog.js';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const OUTPUT = path.join(ROOT, 'docs/research-report.md');
const check = process.argv.includes('--check');
const { catalog, root: catalogRoot } = await loadCatalog();
const rows = [];

for (const scenario of catalog.scenarios) {
  const [mv2, mv3] = await Promise.all([
    auditExtension(path.resolve(catalogRoot, scenario.fixtures.mv2)),
    auditExtension(path.resolve(catalogRoot, scenario.fixtures.mv3))
  ]);
  rows.push({ scenario, mv2, mv3 });
}

const countEffects = Object.fromEntries([...new Set(rows.map(({ scenario }) => scenario.mv3Effect))].sort().map((effect) => [effect, rows.filter(({ scenario }) => scenario.mv3Effect === effect).length]));
const lines = [
  '# Generated corpus report', '',
  '> This file is generated by `npm run docs:generate`. It reports static fixture capabilities, not measured exploit success rates.', '',
  `Catalog version: ${catalog.version}  `,
  `Scenarios: ${rows.length} (${rows.length * 2} non-executing fixtures)`, '',
  '## MV3 effect taxonomy', '',
  '| Effect | Scenarios | Meaning |', '|---|---:|---|',
  ...Object.entries(countEffects).map(([effect, count]) => `| ${effect} | ${count} | ${catalog.effectDefinitions[effect]} |`), '',
  '## Capability matrix', '',
  '| Scenario | Category | MV3 effect | MV2 risk | MV3 risk |', '|---|---|---|---:|---:|',
  ...rows.map(({ scenario, mv2, mv3 }) => `| ${scenario.title} | ${scenario.category} | ${scenario.mv3Effect} | ${mv2.summary.riskScore} | ${mv3.summary.riskScore} |`), '',
  '## Interpretation limits', '',
  '- A fixture demonstrates that the analyzer recognizes a declared capability or source pattern; it is not executed by this project.',
  '- Scores prioritize review effort. They are not probabilities, exploitability measurements, or Chrome Web Store verdicts.',
  '- “Unchanged” means the relevant capability remains available when permission is granted, not that MV2 and MV3 are identical.',
  '- Browser runtime behavior must be tested separately in a pinned, isolated environment before making empirical claims.', ''
];
const generated = lines.join('\n');

if (check) {
  let existing = '';
  try { existing = await readFile(OUTPUT, 'utf8'); } catch {}
  if (existing !== generated) {
    process.stderr.write('docs/research-report.md is stale; run npm run docs:generate\n');
    process.exitCode = 1;
  } else process.stdout.write('Generated report is up to date\n');
} else {
  await writeFile(OUTPUT, generated, 'utf8');
  process.stdout.write(`Wrote ${path.relative(ROOT, OUTPUT)}\n`);
}

